DROP TABLE IF EXISTS cakes CASCADE;

CREATE TABLE cakes (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  cake_photo_url VARCHAR(255) NOT NULL,
  title VARCHAR(70) NOT NULL,
  description VARCHAR(100) NOT NULL,
  price INTEGER  NOT NULL DEFAULT 0,
  posted_date TIMESTAMP NOT NULL DEFAULT NOW(),
  cake_status VARCHAR(20) NOT NULL DEFAULT "Available"
);
