DROP TABLE IF EXISTS fav_cakes CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  cake_id INTEGER REFERENCES cakes(id) ON DELETE CASCADE,
);
